src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[Broadcast]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_couverture = null;

    #[ORM\Column(length: 255)]
    private ?string $date_creation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $moyenne_avis = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImageCouverture(): ?string
    {
        return $this->image_couverture;
    }

    public function setImageCouverture(?string $image_couverture): static
    {
        $this->image_couverture = $image_couverture;

        return $this;
    }

    public function getDateCreation(): ?string
    {
        return $this->date_creation;
    }

    public function setDateCreation(string $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getMoyenneAvis(): ?string
    {
        return $this->moyenne_avis;
    }

    public function setMoyenneAvis(?string $moyenne_avis): static
    {
        $this->moyenne_avis = $moyenne_avis;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('image_couverture')
            ->add('date_creation')
            ->add('moyenne_avis')
            ->add('categorie')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    <h1>Produit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Image_couverture</th>
                <th>Date_creation</th>
                <th>Moyenne_avis</th>
                <th>Categorie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.titre }}</td>
                <td>{{ produit.description }}</td>
                <td>{{ produit.imageCouverture }}</td>
                <td>{{ produit.dateCreation }}</td>
                <td>{{ produit.moyenneAvis }}</td>
                <td>{{ produit.categorie }}</td>
                <td>
                    <a href="{{ path('app_produit_show', {'id': produit.id}) }}">show</a>
                    <a href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_produit_new') }}">Create new</a>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('app_produit_index') }}">back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ produit.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.description }}</td>
            </tr>
            <tr>
                <th>Image_couverture</th>
                <td>{{ produit.imageCouverture }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ produit.dateCreation }}</td>
            </tr>
            <tr>
                <th>Moyenne_avis</th>
                <td>{{ produit.moyenneAvis }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ produit.categorie }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_produit_index') }}">back to list</a>

    <a href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}